ALTER TABLE olts ADD COLUMN IF NOT EXISTS last_test_status TEXT NOT NULL DEFAULT '';
ALTER TABLE olts ADD COLUMN IF NOT EXISTS last_tested_at TIMESTAMPTZ;
ALTER TABLE olts ADD COLUMN IF NOT EXISTS last_test_detail TEXT NOT NULL DEFAULT '';
